# Generated by Django 4.2 on 2023-04-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_size', models.IntegerField(default=3000)),
                ('usage', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('key', models.TextField()),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('exp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certSha256', models.TextField()),
                ('apiUrl', models.CharField(max_length=255)),
            ],
        ),
    ]
