# Generated by Django 4.2 on 2023-04-27 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0002_link_note_link_pastebin_link_server_wrapper_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outline.server'),
        ),
    ]
