# Generated by Django 4.2 on 2023-04-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0003_link_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(default='None', max_length=125),
        ),
        migrations.AlterField(
            model_name='server',
            name='certSha256',
            field=models.TextField(blank=True),
        ),
    ]
