# Generated by Django 4.2 on 2023-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0004_server_name_alter_server_certsha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='outline_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='usage',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
