# Generated by Django 4.2 on 2023-05-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0006_channel_server_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
