# Generated by Django 4.2 on 2023-05-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0007_channel_name_alter_channel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='wrapper_ip',
            field=models.CharField(default='sub.example.com', max_length=100),
        ),
    ]
